name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compiler les tests de validation
      run: gcc -Wall -o main src/main.c src/aes.c

    - name: Executer les tests de validation
      run: ./main

    - name: Compiler le chiffrement
      run: gcc -Wall -o chiffrer src/chiffrer.c src/aes.c

    - name: Compiler le dechiffrement
      run: gcc -Wall -o dechiffrer src/dechiffrer.c src/aes.c